# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0012_auto_20200108_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
